FROM prom/prometheus
ADD ./prometheus.yml /etc/prometheus/prometheus.yml
CMD [ "--config.file=/etc/prometheus/prometheus.yml" ]


#1 pull the Prometheus from docker 
#2 copy/add the local .yml to image .yaml folder
#3 config the yml 
