# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'grafana'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:3000']

  # - job_name: 'node_exporter'

  #   # metrics_path defaults to '/metrics'
  #   # scheme defaults to 'http'.

  #   static_configs:
  #   - targets: ['localhost:9100']

  # - job_name: 'bitbucket'
  #   scheme: http #change to http if don't you have https
  #   metrics_path: '/plugins/servlet/prometheus/metrics'
  #   params:
  #   static_configs:
  #     - targets: ['tpsbitbucket.standardbank.co.za:7990']

  - job_name: 'bamboo'
    scheme: http #change to http if don't you have https
    metrics_path: '/plugins/servlet/prometheus/metrics'
    static_configs:
      - targets: ['10.208.69.135:8085']

  - job_name: 'DevServer' #DevServer for the Andon Cord
    scheme: http #change to http if don't you have https
    #metrics_path: '/metrics'
    static_configs:
      - targets: ['10.7.142.55:8080']

  # - job_name: 'DevServerHealth' #DevServer for the Andon Cord Health
  #   scheme: http #change to http if don't you have https
  #   metrics_path: '/health'
  #   static_configs:
  #     - targets: ['10.7.142.55:8080']

  # - job_name: 'sonarqube'
  #   metrics_path: '/api/prometheus/about'
  #   # metrics_path: '/api/prometheus/metrics'
  #   static_configs:
  #     - targets: ['10.147.38.12:9000']
  # scrape_configs:
  - job_name: 'sonarqube'
    metrics_path: '/api/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9000']

 
   
