{
 "title": "Master Build",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Success finished_build",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "COUNT(bamboo_finished_build_count{planKey=~\"MB.*\",planKey!~\"MB-BE1.*\",planKey!~\"MB-BE2.*\",planKey!~\"MB-BEL0.*\",planKey!~\"MB-BEL1.*\",planKey!~\"MB-BL1.*\",planKey!~\"MB-BL2.*\",planKey!~\"MB-BDT1\", planKey!~\"MB-CD2.*\", planKey!~\"MB-CD3.*\", planKey!~\"MB-CL0.*\", planKey!~\"MB-CL1.*\", planKey!~\"MB-FRAM8.*\", planKey!~\"MB-FRAM9.*\", planKey!~\"MB-IA0.*\", planKey!~\"MB-IA1.*\", planKey!~\"MB-N3WB2.*\", planKey!~\"MB-N6WB2.*\", planKey!~\"MB-NBOL7.*\", planKey!~\"MB-NBOL8.*\", planKey!~\"MB-NBU2.*\", planKey!~\"MB-NDB2.*\", planKey!~\"MB-PAYM1.*\", planKey!~\"MB-PAYM7.*\", planKey!~\"MB-PD0.*\", planKey!~\"MB-PD13.*\", planKey!~\"MB-REST2.*\", planKey!~\"MB-REST3.*\", planKey!~\"MB-RG2.*\", planKey!~\"MB-RG3.*\", planKey!~\"MB-SA2.*\", planKey!~\"MB-SA3.*\", planKey!~\"MB-SL0.*\", planKey!~\"MB-SL1.*\", planKey!~\"MB-SM8.*\", planKey!~\"MB-SM9.*\", planKey!~\"MB-SNS0.*\", planKey!~\"MB-SNS1.*\", planKey!~\"MB-SPP0.*\", planKey!~\"MB-SPP1.*\", planKey!~\"MB-STDA2.*\", planKey!~\"MB-STDA3.*\", planKey!~\"MB-TCM1.*\", planKey!~\"MB-TCM8.*\", planKey!~\"MB-TCP0.*\", planKey!~\"MB-TCP2.*\", planKey!~\"MB-TPP1.*\", planKey!~\"MB-TPP2.*\", planKey!~\"MB-WFG0.*\", planKey!~\"MB-WFG1.*\",state=\"SUCCESS\"})"
    }
   ]
  },
  {
   "title": "Failed finished_build",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(bamboo_finished_build_count{planKey=~\"MB.*\",planKey!~\"MB-BE1.*\",planKey!~\"MB-BE2.*\",planKey!~\"MB-BEL0.*\",planKey!~\"MB-BEL1.*\",planKey!~\"MB-BL1.*\",planKey!~\"MB-BL2.*\",planKey!~\"MB-BDT1\", planKey!~\"MB-CD2.*\", planKey!~\"MB-CD3.*\", planKey!~\"MB-CL0.*\", planKey!~\"MB-CL1.*\", planKey!~\"MB-FRAM8.*\", planKey!~\"MB-FRAM9.*\", planKey!~\"MB-IA0.*\", planKey!~\"MB-IA1.*\", planKey!~\"MB-N3WB2.*\", planKey!~\"MB-N6WB2.*\", planKey!~\"MB-NBOL7.*\", planKey!~\"MB-NBOL8.*\", planKey!~\"MB-NBU2.*\", planKey!~\"MB-NDB2.*\", planKey!~\"MB-PAYM1.*\", planKey!~\"MB-PAYM7.*\", planKey!~\"MB-PD0.*\", planKey!~\"MB-PD13.*\", planKey!~\"MB-REST2.*\", planKey!~\"MB-REST3.*\", planKey!~\"MB-RG2.*\", planKey!~\"MB-RG3.*\", planKey!~\"MB-SA2.*\", planKey!~\"MB-SA3.*\", planKey!~\"MB-SL0.*\", planKey!~\"MB-SL1.*\", planKey!~\"MB-SM8.*\", planKey!~\"MB-SM9.*\", planKey!~\"MB-SNS0.*\", planKey!~\"MB-SNS1.*\", planKey!~\"MB-SPP0.*\", planKey!~\"MB-SPP1.*\", planKey!~\"MB-STDA2.*\", planKey!~\"MB-STDA3.*\", planKey!~\"MB-TCM1.*\", planKey!~\"MB-TCM8.*\", planKey!~\"MB-TCP0.*\", planKey!~\"MB-TCP2.*\", planKey!~\"MB-TPP1.*\", planKey!~\"MB-TPP2.*\", planKey!~\"MB-WFG0.*\", planKey!~\"MB-WFG1.*\",state=\"FAILED\"})"
    }
   ]
  },
  {
   "title": "Bamboo Canceled Build Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(bamboo_canceled_build_count)"
    }
   ]
  },
  {
   "title": "Master Build Failed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bamboo_finished_build_count{planKey=~\"MB.*\",planKey!~\"MB-BE1.*\",planKey!~\"MB-BE2.*\",planKey!~\"MB-BEL0.*\",planKey!~\"MB-BEL1.*\",planKey!~\"MB-BL1.*\",planKey!~\"MB-BL2.*\",planKey!~\"MB-BDT1\", planKey!~\"MB-CD2.*\", planKey!~\"MB-CD3.*\", planKey!~\"MB-CL0.*\", planKey!~\"MB-CL1.*\", planKey!~\"MB-FRAM8.*\", planKey!~\"MB-FRAM9.*\", planKey!~\"MB-IA0.*\", planKey!~\"MB-IA1.*\", planKey!~\"MB-N3WB2.*\", planKey!~\"MB-N6WB2.*\", planKey!~\"MB-NBOL7.*\", planKey!~\"MB-NBOL8.*\", planKey!~\"MB-NBU2.*\", planKey!~\"MB-NDB2.*\", planKey!~\"MB-PAYM1.*\", planKey!~\"MB-PAYM7.*\", planKey!~\"MB-PD0.*\", planKey!~\"MB-PD13.*\", planKey!~\"MB-REST2.*\", planKey!~\"MB-REST3.*\", planKey!~\"MB-RG2.*\", planKey!~\"MB-RG3.*\", planKey!~\"MB-SA2.*\", planKey!~\"MB-SA3.*\", planKey!~\"MB-SL0.*\", planKey!~\"MB-SL1.*\", planKey!~\"MB-SM8.*\", planKey!~\"MB-SM9.*\", planKey!~\"MB-SNS0.*\", planKey!~\"MB-SNS1.*\", planKey!~\"MB-SPP0.*\", planKey!~\"MB-SPP1.*\", planKey!~\"MB-STDA2.*\", planKey!~\"MB-STDA3.*\", planKey!~\"MB-TCM1.*\", planKey!~\"MB-TCM8.*\", planKey!~\"MB-TCP0.*\", planKey!~\"MB-TCP2.*\", planKey!~\"MB-TPP1.*\", planKey!~\"MB-TPP2.*\", planKey!~\"MB-WFG0.*\", planKey!~\"MB-WFG1.*\",state=\"FAILED\"}[5m])",
     "legendFormat": "{{planKey}}"
    }
   ]
  },
  {
   "title": "Payment",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bamboo_finished_build_count{planKey=~\"MB-PAYM.*\",planKey!~\"MB-PAYM1.*\",planKey!~\"MB-PAYM7.*\"}[5m])",
     "legendFormat": "PAYMENT-{{state}}"
    }
   ]
  },
  {
   "title": "Nbol",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bamboo_finished_build_count{planKey=~\"MB-NBOL.*\",planKey!~\"MB-NBOL7.*\",planKey!~\"MB-NBOL8.*\"}[5m])",
     "legendFormat": "NBOL- {{state}}"
    }
   ]
  },
  {
   "title": "Statement",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bamboo_finished_build_count{planKey=~\"MB-SM.*\",planKey!~\"MB-SM8.*\",planKey!~\"MB-SM9.*\"}[5m])",
     "legendFormat": "STATEMENT- {{state}}"
    }
   ]
  },
  {
   "title": "Master All Build Success",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bamboo_finished_build_count{planKey=~\"MB.*\",planKey!~\"MB-BE1.*\",planKey!~\"MB-BE2.*\",planKey!~\"MB-BEL0.*\",planKey!~\"MB-BEL1.*\",planKey!~\"MB-BL1.*\",planKey!~\"MB-BL2.*\",planKey!~\"MB-BDT1\", planKey!~\"MB-CD2.*\", planKey!~\"MB-CD3.*\", planKey!~\"MB-CL0.*\", planKey!~\"MB-CL1.*\", planKey!~\"MB-FRAM8.*\", planKey!~\"MB-FRAM9.*\", planKey!~\"MB-IA0.*\", planKey!~\"MB-IA1.*\", planKey!~\"MB-N3WB2.*\", planKey!~\"MB-N6WB2.*\", planKey!~\"MB-NBOL7.*\", planKey!~\"MB-NBOL8.*\", planKey!~\"MB-NBU2.*\", planKey!~\"MB-NDB2.*\", planKey!~\"MB-PAYM1.*\", planKey!~\"MB-PAYM7.*\", planKey!~\"MB-PD0.*\", planKey!~\"MB-PD13.*\", planKey!~\"MB-REST2.*\", planKey!~\"MB-REST3.*\", planKey!~\"MB-RG2.*\", planKey!~\"MB-RG3.*\", planKey!~\"MB-SA2.*\", planKey!~\"MB-SA3.*\", planKey!~\"MB-SL0.*\", planKey!~\"MB-SL1.*\", planKey!~\"MB-SM8.*\", planKey!~\"MB-SM9.*\", planKey!~\"MB-SNS0.*\", planKey!~\"MB-SNS1.*\", planKey!~\"MB-SPP0.*\", planKey!~\"MB-SPP1.*\", planKey!~\"MB-STDA2.*\", planKey!~\"MB-STDA3.*\", planKey!~\"MB-TCM1.*\", planKey!~\"MB-TCM8.*\", planKey!~\"MB-TCP0.*\", planKey!~\"MB-TCP2.*\", planKey!~\"MB-TPP1.*\", planKey!~\"MB-TPP2.*\", planKey!~\"MB-WFG0.*\", planKey!~\"MB-WFG1.*\",state=\"SUCCESS\"}[5m])",
     "legendFormat": "{{planKey}}"
    }
   ]
  }
 ]
}